//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCrud.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity.Validation;
    public partial class Inventory
    {
        public int InventoryID { get; set; }
        [DisplayName("Customer Name")]
        public string Name { get; set; }
        [DisplayName("Order Name")]
        public string Ordername { get; set; }
        [DisplayName("Order Quantity")]
        public string Quantity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
